Update docker.yml

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -12,13 +12,23 @@ jobs:
       uses: actions/checkout@v2
 
     - name: Login to Docker Hub
-      uses: docker/login-action@v1
+      uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
-
+    
     - name: Build Docker image
-      run: docker build -t yash2232/project:${{ github.sha }} .
+      run: |
+        docker build -t yash2232/project:${{ github.sha }} .
+        if [ $? -ne 0 ]; then
+          echo "Docker build failed"
+          exit 1
+        fi
 
     - name: Push Docker image to Docker Hub
-      run: docker push yash2232/project:${{ github.sha }}
+      run: |
+        docker push yash2232/project:${{ github.sha }}
+        if [ $? -ne 0 ]; then
+          echo "Docker push failed"
+          exit 1
+        fi
